# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

# Should enable. but not yet.
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false

# Disable
UselessAssignment:
  Enabled: false
SingleLineBlockParams:
  Enabled: false
RegexpLiteral:
  Enabled: false
RescueModifier:
  Enabled: false
TrailingComma:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
FormatString:
  Enabled: false

# For old rubocop version
SymbolName:
  Enabled: false
ReduceArguments:
  Enabled: false

# Avoid check files
AllCops:
  Exclude:
    - db/schema.rb
    - config/**
    - misc/**
    - vendor/**
